name: SettingsLibrary
version: 1.0.0
main: me.mikey.settingslibrary.SettingsLibraryPlugin
api-version: '1.21.10'
author: Mikey
description: A centralized settings UI library for Minecraft plugins

# Commands
commands:
  settings:
    description: Open the main settings menu
    usage: /<command>
    aliases: [settingsmenu, pluginsettings]
  settingslibrary:
    description: Admin commands for SettingsLibrary
    usage: /<command> <list|reload|info>
    aliases: [setlib, slib]

# Permissions
permissions:
  settingslibrary.use:
    description: Allows access to the settings menu
    default: true
  settingslibrary.admin:
    description: Allows access to admin commands
    default: op
  settingslibrary.reload:
    description: Allows reloading the plugin config
    default: op

